export { getProvinceConfig, getMapThemes, setMapTheme, createBMapVGL };
function getProvinceConfig() {
  return {
    北京市: { abbreviation: "北京", zoom: 10, lng: 116.395645, lat: 39.929986 },
    上海市: { abbreviation: "上海", zoom: 10, lng: 121.487899, lat: 31.249162 },
    天津市: { abbreviation: "天津", zoom: 10, lng: 117.210813, lat: 39.14393 },
    重庆市: { abbreviation: "重庆", zoom: 9, lng: 106.530635, lat: 29.544606 },
    河北省: { abbreviation: "河北", zoom: 7, lng: 115.661434, lat: 38.61384 },
    山西省: { abbreviation: "山西", zoom: 7, lng: 112.515496, lat: 37.866566 },
    辽宁省: { abbreviation: "辽宁", zoom: 7, lng: 122.753592, lat: 41.6216 },
    吉林省: { abbreviation: "吉林", zoom: 7, lng: 126.262876, lat: 43.678846 },
    黑龙江省: { abbreviation: "黑龙江", zoom: 7, lng: 128.047414, lat: 47.356592 },
    江苏省: { abbreviation: "江苏", zoom: 8, lng: 119.368489, lat: 33.013797 },
    浙江省: { abbreviation: "浙江", zoom: 8, lng: 119.957202, lat: 29.159494 },
    安徽省: { abbreviation: "安徽", zoom: 8, lng: 117.216005, lat: 31.859252 },
    福建省: { abbreviation: "福建", zoom: 7, lng: 117.984943, lat: 26.050118 },
    江西省: { abbreviation: "江西", zoom: 8, lng: 115.676082, lat: 27.757258 },
    山东省: { abbreviation: "山东", zoom: 8, lng: 118.527663, lat: 36.09929 },
    河南省: { abbreviation: "河南", zoom: 8, lng: 113.486804, lat: 34.157184 },
    湖北省: { abbreviation: "湖北", zoom: 8, lng: 112.410562, lat: 31.209316 },
    湖南省: { abbreviation: "湖南", zoom: 8, lng: 111.720664, lat: 27.695864 },
    广东省: { abbreviation: "广东", zoom: 8, lng: 113.394818, lat: 23.408004 },
    海南省: { abbreviation: "海南", zoom: 9, lng: 109.733755, lat: 19.180501 },
    四川省: { abbreviation: "四川", zoom: 7, lng: 102.89916, lat: 30.367481 },
    贵州省: { abbreviation: "贵州", zoom: 8, lng: 106.734996, lat: 26.902826 },
    云南省: { abbreviation: "云南", zoom: 7, lng: 101.592952, lat: 24.864213 },
    陕西省: { abbreviation: "陕西", zoom: 7, lng: 109.503789, lat: 35.860026 },
    甘肃省: { abbreviation: "甘肃", zoom: 6, lng: 102.457625, lat: 38.103267 },
    青海省: { abbreviation: "青海", zoom: 7, lng: 96.202544, lat: 35.499761 },
    台湾省: { abbreviation: "台湾", zoom: 8, lng: 120.961454, lat: 23.80406 },
    内蒙古自治区: { abbreviation: "内蒙古", zoom: 6, lng: 114.415868, lat: 43.468238 },
    广西壮族自治区: { abbreviation: "广西", zoom: 8, lng: 108.924274, lat: 23.552255 },
    宁夏回族自治区: { abbreviation: "宁夏", zoom: 8, lng: 106.155481, lat: 37.321323 },
    新疆维吾尔自治区: { abbreviation: "新疆", zoom: 6, lng: 85.614899, lat: 42.127001 },
    西藏自治区: { abbreviation: "西藏", zoom: 6, lng: 89.137982, lat: 31.367315 },
    香港特别行政区: { abbreviation: "香港", zoom: 7, lng: 114.186124, lat: 22.293586 },
    澳门特别行政区: { abbreviation: "澳门", zoom: 7, lng: 113.557519, lat: 22.204118 },
  };
}
function getMapThemes() {
  return [
    { label: "深黑", value: "darkStyle" },
    { label: "紫灰", value: "purpleStyle" },
    { label: "雪白", value: "snowStyle" },
    { label: "灰白", value: "whiteStyle" },
  ];
}
function setMapTheme(e, l) {
  mapThemeConfig[l] && e.setMapStyleV2({ styleJson: mapThemeConfig[l] });
}
async function createBMapVGL(e, l, t) {
  let y,
    i = null;
  return (
    await loadBMapGL(e).then((e) => {
      ((y = initMap(l, t)), (i = new mapvgl.View({ map: y })));
    }),
    { map: y, view: i, BMapGL: BMapGL, mapv: mapv, mapvgl: mapvgl }
  );
}
function loadBMapGL(e) {
  return new Promise((l, t) => {
    try {
      l(BMapGL);
    } catch (y) {
      window.init = () => {
        l(BMapGL);
      };
      const i = document.createElement("script");
      ((i.type = "text/javascript"),
        (i.src = `https://api.map.baidu.com/api?v=1.0&type=webgl&ak=${e}&callback=init`),
        (i.onerror = t),
        document.head.appendChild(i));
      const r = document.createElement("script");
      ((r.type = "text/javascript"),
        (r.src = "https://mapv.baidu.com/build/mapv.min.js"),
        (r.onerror = t),
        document.head.appendChild(r));
      const f = document.createElement("script");
      ((f.type = "text/javascript"),
        (f.src = "https://code.bdstatic.com/npm/mapvgl@1.0.0-beta.131/dist/mapvgl.min.js"),
        (f.onerror = t),
        document.head.appendChild(f));
    }
  });
}
function initMap(e, l) {
  l = Object.assign({ tilt: 60, heading: 0 }, l);
  const t = new BMapGL.Map(e, {
    restrictCenter: !1,
    style: { styleJson: mapThemeConfig[l.themeName] || mapThemeConfig.darkStyle },
  });
  return (
    t.enableKeyboard(),
    t.enableScrollWheelZoom(),
    t.enableInertialDragging(),
    t.enableContinuousZoom(),
    t.setDisplayOptions(
      l.displayOptions || {
        indoor: !1,
        poi: !0,
        skyColors: l.skyColors || ["rgba(5, 5, 30, 0.01)", "rgba(5, 5, 30, 1.0)"],
      },
    ),
    l.center && l.zoom && t.centerAndZoom(new BMapGL.Point(l.center[0], l.center[1]), l.zoom),
    t.setTilt(l.tilt),
    t.setHeading(l.heading),
    t
  );
}
const mapThemeConfig = {
  darkStyle: [
    { featureType: "background", elementType: "geometry", stylers: { color: "#070c17ff" } },
    { featureType: "poilabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "road", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "road", elementType: "geometry.fill", stylers: { color: "#151e25ff" } },
    { featureType: "road", elementType: "geometry.stroke", stylers: { color: "#ffffff00" } },
    { featureType: "highway", elementType: "geometry.fill", stylers: { color: "#27303bff" } },
    { featureType: "highway", elementType: "geometry.stroke", stylers: { color: "#ffffff00" } },
    { featureType: "nationalway", elementType: "geometry.fill", stylers: { color: "#27303bff" } },
    { featureType: "nationalway", elementType: "geometry.stroke", stylers: { color: "#ffffff00" } },
    { featureType: "provincialway", elementType: "geometry.fill", stylers: { color: "#27303bff" } },
    {
      featureType: "provincialway",
      elementType: "geometry.stroke",
      stylers: { color: "#ffffff00" },
    },
    { featureType: "railway", elementType: "geometry", stylers: { visibility: "off" } },
    { featureType: "highwaysign", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "highwaysign", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "nationalwaysign", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "nationalwaysign", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "provincialwaysign", elementType: "labels", stylers: { visibility: "off" } },
    {
      featureType: "provincialwaysign",
      elementType: "labels.icon",
      stylers: { visibility: "off" },
    },
    { featureType: "tertiarywaysign", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "tertiarywaysign", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "subwaylabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "subwaylabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "poilabel", elementType: "labels.text.fill", stylers: { color: "#80868dff" } },
    { featureType: "poilabel", elementType: "labels.text.stroke", stylers: { color: "#ffffff00" } },
    {
      featureType: "districtlabel",
      elementType: "labels.text.fill",
      stylers: { color: "#71767aff" },
    },
    {
      featureType: "districtlabel",
      elementType: "labels.text.stroke",
      stylers: { color: "#ffffff00" },
    },
    { featureType: "poilabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "airportlabel", elementType: "labels", stylers: { visibility: "on" } },
    { featureType: "airportlabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    {
      featureType: "airportlabel",
      elementType: "labels.text.fill",
      stylers: { color: "#80868dff" },
    },
    {
      featureType: "airportlabel",
      elementType: "labels.text.stroke",
      stylers: { color: "#ffffff00" },
    },
    { featureType: "manmade", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "manmade", elementType: "geometry", stylers: { color: "#070c17ff" } },
    { featureType: "water", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "water", elementType: "geometry", stylers: { color: "#141d27ff" } },
    {
      featureType: "green",
      elementType: "geometry",
      stylers: { color: "#122228ff", visibility: "off" },
    },
    { featureType: "subway", elementType: "geometry", stylers: { visibility: "off" } },
    { featureType: "highway", elementType: "labels", stylers: { visibility: "on" } },
    { featureType: "highway", elementType: "labels.text.stroke", stylers: { color: "#ffffff00" } },
    { featureType: "highway", elementType: "labels.text.fill", stylers: { color: "#5f6468ff" } },
    { featureType: "town", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "village", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "highway", elementType: "geometry", stylers: { weight: 3 } },
    { featureType: "cityhighway", elementType: "geometry.fill", stylers: { color: "#27303bff" } },
    { featureType: "arterial", elementType: "geometry.fill", stylers: { color: "#27303bff" } },
    { featureType: "arterial", elementType: "geometry.stroke", stylers: { color: "#ffffff00" } },
    { featureType: "cityhighway", elementType: "geometry.stroke", stylers: { color: "#ffffff00" } },
  ],
  purpleStyle: [
    { featureType: "water", elementType: "all", stylers: { color: "#021019ff" } },
    { featureType: "highway", elementType: "geometry.fill", stylers: { color: "#000000ff" } },
    { featureType: "highway", elementType: "geometry.stroke", stylers: { color: "#147a92ff" } },
    { featureType: "arterial", elementType: "geometry.fill", stylers: { color: "#000000ff" } },
    { featureType: "arterial", elementType: "geometry.stroke", stylers: { color: "#0b3d51ff" } },
    { featureType: "local", elementType: "geometry", stylers: { color: "#000000ff" } },
    { featureType: "railway", elementType: "geometry.fill", stylers: { color: "#000000ff" } },
    { featureType: "railway", elementType: "geometry.stroke", stylers: { color: "#08304bff" } },
    { featureType: "subway", elementType: "geometry", stylers: { visibility: "off" } },
    { featureType: "all", elementType: "labels.text.fill", stylers: { color: "#857f7fff" } },
    { featureType: "all", elementType: "labels.text.stroke", stylers: { color: "#000000ff" } },
    { featureType: "green", elementType: "geometry", stylers: { color: "#062032ff" } },
    { featureType: "manmade", elementType: "geometry", stylers: { color: "#022338ff" } },
    { featureType: "poilabel", elementType: "all", stylers: { visibility: "off" } },
    { featureType: "all", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "water", elementType: "all", stylers: { visibility: "on", color: "#505565ff" } },
    { featureType: "green", elementType: "all", stylers: { color: "#353b4dff" } },
    {
      featureType: "road",
      elementType: "geometry.fill",
      stylers: { visibility: "on", color: "#2a2e3bff" },
    },
    { featureType: "road", elementType: "geometry.stroke", stylers: { color: "#4b5163ff" } },
    {
      featureType: "administrative",
      elementType: "labels.text.fill",
      stylers: { color: "#8e99bdff" },
    },
    {
      featureType: "administrative",
      elementType: "labels.text.stroke",
      stylers: { color: "#2f3547ff" },
    },
    { featureType: "poilabel", elementType: "labels.text.fill", stylers: { color: "#727c9aff" } },
    { featureType: "road", elementType: "labels.text.stroke", stylers: { color: "#293045ff" } },
    { featureType: "road", elementType: "labels.text.fill", stylers: { color: "#777e93ff" } },
    { featureType: "town", elementType: "all", stylers: { visibility: "on" } },
    {
      featureType: "subway",
      elementType: "labels.text.fill",
      stylers: { visibility: "off", color: "#787f95ff" },
    },
    { featureType: "subway", elementType: "labels.text.stroke", stylers: { color: "#40475eff" } },
    { featureType: "building", elementType: "geometry.fill", stylers: { color: "#485161ff" } },
    { featureType: "manmade", elementType: "geometry.fill", stylers: { color: "#374053ff" } },
    { featureType: "manmade", elementType: "labels.text.fill", stylers: { color: "#8792adff" } },
    { featureType: "manmade", elementType: "labels.text.stroke", stylers: { color: "#292f48ff" } },
    { featureType: "scenicspotslabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "railway", elementType: "geometry", stylers: { visibility: "off" } },
    { featureType: "scenicspotslabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "highwaysign", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "highwaysign", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "nationalwaysign", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "nationalwaysign", elementType: "labels", stylers: { visibility: "off" } },
    {
      featureType: "provincialwaysign",
      elementType: "labels.icon",
      stylers: { visibility: "off" },
    },
    { featureType: "provincialwaysign", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "tertiarywaysign", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "tertiarywaysign", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "subwaylabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "subwaylabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "village", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "town", elementType: "labels", stylers: { visibility: "off" } },
    {
      featureType: "land",
      elementType: "geometry",
      stylers: { color: "#40495aff", visibility: "on" },
    },
  ],
  snowStyle: [
    { featureType: "background", elementType: "geometry", stylers: { color: "#fefefeff" } },
    { featureType: "poilabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "road", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "road", elementType: "geometry.fill", stylers: { color: "#f0f1f7ff" } },
    { featureType: "road", elementType: "geometry.stroke", stylers: { color: "#ffffff00" } },
    { featureType: "highway", elementType: "geometry.fill", stylers: { color: "#e8eaf5ff" } },
    { featureType: "highway", elementType: "geometry.stroke", stylers: { color: "#ffffff00" } },
    { featureType: "nationalway", elementType: "geometry.fill", stylers: { color: "#e8eaf5ff" } },
    { featureType: "nationalway", elementType: "geometry.stroke", stylers: { color: "#ffffff00" } },
    { featureType: "provincialway", elementType: "geometry.fill", stylers: { color: "#e8eaf5ff" } },
    {
      featureType: "provincialway",
      elementType: "geometry.stroke",
      stylers: { color: "#ffffff00" },
    },
    { featureType: "railway", elementType: "geometry", stylers: { visibility: "off" } },
    { featureType: "highwaysign", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "highwaysign", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "nationalwaysign", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "nationalwaysign", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "provincialwaysign", elementType: "labels", stylers: { visibility: "off" } },
    {
      featureType: "provincialwaysign",
      elementType: "labels.icon",
      stylers: { visibility: "off" },
    },
    { featureType: "tertiarywaysign", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "tertiarywaysign", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "subwaylabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "subwaylabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "poilabel", elementType: "labels.text.fill", stylers: { color: "#80868dff" } },
    { featureType: "poilabel", elementType: "labels.text.stroke", stylers: { color: "#ffffff00" } },
    {
      featureType: "districtlabel",
      elementType: "labels.text.fill",
      stylers: { color: "#7d82b0ff" },
    },
    {
      featureType: "districtlabel",
      elementType: "labels.text.stroke",
      stylers: { color: "#ffffff00" },
    },
    { featureType: "poilabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "airportlabel", elementType: "labels", stylers: { visibility: "on" } },
    { featureType: "airportlabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    {
      featureType: "airportlabel",
      elementType: "labels.text.fill",
      stylers: { color: "#80868dff" },
    },
    {
      featureType: "airportlabel",
      elementType: "labels.text.stroke",
      stylers: { color: "#ffffff00" },
    },
    { featureType: "manmade", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "manmade", elementType: "geometry", stylers: { color: "#eef1fbff" } },
    { featureType: "water", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "water", elementType: "geometry", stylers: { color: "#a7c9ffff" } },
    {
      featureType: "green",
      elementType: "geometry",
      stylers: { color: "#eef1fbff", visibility: "off" },
    },
    { featureType: "subway", elementType: "geometry", stylers: { visibility: "off" } },
    { featureType: "highway", elementType: "labels", stylers: { visibility: "on" } },
    { featureType: "highway", elementType: "labels.text.stroke", stylers: { color: "#ffffff00" } },
    { featureType: "highway", elementType: "labels.text.fill", stylers: { color: "#7d82b0ff" } },
    { featureType: "town", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "village", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "highway", elementType: "geometry", stylers: { weight: 3 } },
    { featureType: "cityhighway", elementType: "geometry.fill", stylers: { color: "#e8eaf5ff" } },
    { featureType: "arterial", elementType: "geometry.fill", stylers: { color: "#e8eaf5ff" } },
    { featureType: "arterial", elementType: "geometry.stroke", stylers: { color: "#ffffff00" } },
    { featureType: "cityhighway", elementType: "geometry.stroke", stylers: { color: "#ffffff00" } },
  ],
  whiteStyle: [
    {
      featureType: "water",
      elementType: "geometry",
      stylers: { visibility: "on", color: "#ccd6d7ff" },
    },
    {
      featureType: "green",
      elementType: "geometry",
      stylers: { visibility: "on", color: "#dee5e5ff" },
    },
    { featureType: "building", elementType: "geometry", stylers: { visibility: "on" } },
    { featureType: "building", elementType: "geometry.fill", stylers: { color: "#d1dbdbff" } },
    { featureType: "building", elementType: "geometry.stroke", stylers: { color: "#aab6b6ff" } },
    {
      featureType: "subwaystation",
      elementType: "geometry",
      stylers: { visibility: "off", color: "#888fa0ff" },
    },
    {
      featureType: "education",
      elementType: "geometry",
      stylers: { visibility: "on", color: "#e1e7e7ff" },
    },
    {
      featureType: "medical",
      elementType: "geometry",
      stylers: { visibility: "on", color: "#d1dbdbff" },
    },
    {
      featureType: "scenicspots",
      elementType: "geometry",
      stylers: { visibility: "on", color: "#d1dbdbff" },
    },
    { featureType: "highway", elementType: "geometry", stylers: { visibility: "on", weight: "4" } },
    { featureType: "highway", elementType: "geometry.fill", stylers: { color: "#ffffffff" } },
    { featureType: "highway", elementType: "geometry.stroke", stylers: { color: "#cacfcfff" } },
    { featureType: "highway", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "highway", elementType: "labels.text.fill", stylers: { color: "#999999ff" } },
    { featureType: "highway", elementType: "labels.text.stroke", stylers: { color: "#ffffffff" } },
    { featureType: "highway", elementType: "labels.icon", stylers: { visibility: "on" } },
    {
      featureType: "arterial",
      elementType: "geometry",
      stylers: { visibility: "on", weight: "2" },
    },
    { featureType: "arterial", elementType: "geometry.fill", stylers: { color: "#fbfffeff" } },
    { featureType: "arterial", elementType: "geometry.stroke", stylers: { color: "#cacfcfff" } },
    { featureType: "arterial", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "arterial", elementType: "labels.text.fill", stylers: { color: "#999999ff" } },
    { featureType: "arterial", elementType: "labels.text.stroke", stylers: { color: "#ffffffff" } },
    { featureType: "local", elementType: "geometry", stylers: { visibility: "on", weight: "1" } },
    { featureType: "local", elementType: "geometry.fill", stylers: { color: "#fbfffeff" } },
    { featureType: "local", elementType: "geometry.stroke", stylers: { color: "#cacfcfff" } },
    { featureType: "local", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "local", elementType: "labels.text.fill", stylers: { color: "#999999ff" } },
    { featureType: "local", elementType: "labels.text.stroke", stylers: { color: "#ffffffff" } },
    {
      featureType: "railway",
      elementType: "geometry",
      stylers: { visibility: "off", weight: "1" },
    },
    { featureType: "railway", elementType: "geometry.fill", stylers: { color: "#9494941a" } },
    { featureType: "railway", elementType: "geometry.stroke", stylers: { color: "#ffffff1a" } },
    { featureType: "subway", elementType: "geometry", stylers: { visibility: "off", weight: "1" } },
    { featureType: "subway", elementType: "geometry.fill", stylers: { color: "#c3bed433" } },
    { featureType: "subway", elementType: "geometry.stroke", stylers: { color: "#ffffff33" } },
    { featureType: "subway", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "subway", elementType: "labels.text.fill", stylers: { color: "#979c9aff" } },
    { featureType: "subway", elementType: "labels.text.stroke", stylers: { color: "#ffffffff" } },
    { featureType: "continent", elementType: "labels", stylers: { visibility: "on" } },
    { featureType: "continent", elementType: "labels.icon", stylers: { visibility: "on" } },
    { featureType: "continent", elementType: "labels.text.fill", stylers: { color: "#333333ff" } },
    {
      featureType: "continent",
      elementType: "labels.text.stroke",
      stylers: { color: "#ffffffff" },
    },
    { featureType: "city", elementType: "labels.icon", stylers: { visibility: "on" } },
    { featureType: "city", elementType: "labels", stylers: { visibility: "on" } },
    { featureType: "city", elementType: "labels.text.fill", stylers: { color: "#454d50ff" } },
    { featureType: "city", elementType: "labels.text.stroke", stylers: { color: "#ffffffff" } },
    { featureType: "town", elementType: "labels.icon", stylers: { visibility: "on" } },
    { featureType: "town", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "town", elementType: "labels.text.fill", stylers: { color: "#454d50ff" } },
    { featureType: "town", elementType: "labels.text.stroke", stylers: { color: "#ffffffff" } },
    { featureType: "road", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "road", elementType: "geometry.fill", stylers: { color: "#fbfffeff" } },
    { featureType: "poilabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "districtlabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "poilabel", elementType: "labels.text.fill", stylers: { color: "#999999ff" } },
    {
      featureType: "districtlabel",
      elementType: "labels.text.fill",
      stylers: { color: "#888fa0ff" },
    },
    { featureType: "transportation", elementType: "geometry", stylers: { color: "#d1dbdbff" } },
    { featureType: "companylabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "restaurantlabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "lifeservicelabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "carservicelabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "financelabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "otherlabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "village", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "district", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "land", elementType: "geometry", stylers: { color: "#edf3f3ff" } },
    { featureType: "nationalway", elementType: "geometry.stroke", stylers: { color: "#cacfcfff" } },
    {
      featureType: "provincialway",
      elementType: "geometry.stroke",
      stylers: { color: "#cacfcfff" },
    },
    { featureType: "cityhighway", elementType: "geometry.stroke", stylers: { color: "#cacfcfff" } },
    { featureType: "road", elementType: "geometry.stroke", stylers: { color: "#cacfcfff" } },
    { featureType: "subwaylabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "subwaylabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "tertiarywaysign", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "tertiarywaysign", elementType: "labels", stylers: { visibility: "off" } },
    {
      featureType: "provincialwaysign",
      elementType: "labels.icon",
      stylers: { visibility: "off" },
    },
    { featureType: "provincialwaysign", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "nationalwaysign", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "nationalwaysign", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "highwaysign", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "highwaysign", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "nationalway", elementType: "geometry.fill", stylers: { color: "#fbfffeff" } },
    {
      featureType: "nationalway",
      elementType: "labels.text.fill",
      stylers: { color: "#999999ff" },
    },
    {
      featureType: "provincialway",
      elementType: "labels.text.fill",
      stylers: { color: "#999999ff" },
    },
    {
      featureType: "cityhighway",
      elementType: "labels.text.fill",
      stylers: { color: "#999999ff" },
    },
    {
      featureType: "cityhighway",
      elementType: "labels.text.stroke",
      stylers: { color: "#ffffffff" },
    },
    { featureType: "highway", stylers: { level: "6", curZoomRegionId: "0", curZoomRegion: "6-8" } },
    { featureType: "highway", stylers: { level: "7", curZoomRegionId: "0", curZoomRegion: "6-8" } },
    { featureType: "highway", stylers: { level: "8", curZoomRegionId: "0", curZoomRegion: "6-8" } },
    {
      featureType: "highway",
      elementType: "geometry",
      stylers: { visibility: "off", level: "6", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "highway",
      elementType: "geometry",
      stylers: { visibility: "off", level: "7", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "highway",
      elementType: "geometry",
      stylers: { visibility: "off", level: "8", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "highway",
      elementType: "labels",
      stylers: { visibility: "off", level: "6", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "highway",
      elementType: "labels",
      stylers: { visibility: "off", level: "7", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "highway",
      elementType: "labels",
      stylers: { visibility: "off", level: "8", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "nationalway",
      stylers: { level: "6", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "nationalway",
      stylers: { level: "7", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "nationalway",
      stylers: { level: "8", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "nationalway",
      elementType: "geometry",
      stylers: { visibility: "off", level: "6", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "nationalway",
      elementType: "geometry",
      stylers: { visibility: "off", level: "7", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "nationalway",
      elementType: "geometry",
      stylers: { visibility: "off", level: "8", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "nationalway",
      elementType: "labels",
      stylers: { visibility: "off", level: "6", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "nationalway",
      elementType: "labels",
      stylers: { visibility: "off", level: "7", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "nationalway",
      elementType: "labels",
      stylers: { visibility: "off", level: "8", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "provincialway",
      stylers: { level: "8", curZoomRegionId: "0", curZoomRegion: "8-8" },
    },
    {
      featureType: "provincialway",
      elementType: "geometry",
      stylers: { visibility: "off", level: "8", curZoomRegionId: "0", curZoomRegion: "8-8" },
    },
    {
      featureType: "provincialway",
      elementType: "labels",
      stylers: { visibility: "off", level: "8", curZoomRegionId: "0", curZoomRegion: "8-8" },
    },
    {
      featureType: "cityhighway",
      stylers: { level: "6", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "cityhighway",
      stylers: { level: "7", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "cityhighway",
      stylers: { level: "8", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "cityhighway",
      elementType: "geometry",
      stylers: { visibility: "off", level: "6", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "cityhighway",
      elementType: "geometry",
      stylers: { visibility: "off", level: "7", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "cityhighway",
      elementType: "geometry",
      stylers: { visibility: "off", level: "8", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "cityhighway",
      elementType: "labels",
      stylers: { visibility: "off", level: "6", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "cityhighway",
      elementType: "labels",
      stylers: { visibility: "off", level: "7", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    {
      featureType: "cityhighway",
      elementType: "labels",
      stylers: { visibility: "off", level: "8", curZoomRegionId: "0", curZoomRegion: "6-8" },
    },
    { featureType: "cityhighway", elementType: "geometry.fill", stylers: { color: "#fbfffeff" } },
    { featureType: "water", elementType: "labels.text.fill", stylers: { color: "#8f5a33ff" } },
    { featureType: "water", elementType: "labels.text.stroke", stylers: { color: "#ffffffff" } },
    { featureType: "country", elementType: "labels.text.fill", stylers: { color: "#8f5a33ff" } },
    { featureType: "country", elementType: "labels.text.stroke", stylers: { color: "#ffffffff" } },
    { featureType: "country", elementType: "labels.text", stylers: { fontsize: "28" } },
    { featureType: "manmade", elementType: "geometry", stylers: { color: "#dfe7e7ff" } },
    { featureType: "provincialway", elementType: "geometry.fill", stylers: { color: "#fbfffeff" } },
    { featureType: "tertiaryway", elementType: "geometry.fill", stylers: { color: "#fbfffeff" } },
    { featureType: "manmade", elementType: "labels.text.fill", stylers: { color: "#999999ff" } },
    { featureType: "manmade", elementType: "labels.text.stroke", stylers: { color: "#ffffffff" } },
    {
      featureType: "scenicspots",
      elementType: "labels.text.fill",
      stylers: { color: "#999999ff" },
    },
    {
      featureType: "scenicspots",
      elementType: "labels.text.stroke",
      stylers: { color: "#ffffffff" },
    },
    {
      featureType: "airportlabel",
      elementType: "labels.text.fill",
      stylers: { color: "#999999ff" },
    },
    { featureType: "airportlabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    {
      featureType: "scenicspotslabel",
      elementType: "labels.text.fill",
      stylers: { color: "#999999ff" },
    },
    { featureType: "scenicspotslabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    {
      featureType: "educationlabel",
      elementType: "labels.text.fill",
      stylers: { color: "#999999ff" },
    },
    { featureType: "educationlabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    {
      featureType: "medicallabel",
      elementType: "labels.text.fill",
      stylers: { color: "#999999ff" },
    },
    { featureType: "medicallabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "companylabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "restaurantlabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "hotellabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "hotellabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "shoppinglabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "shoppinglabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "lifeservicelabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "carservicelabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    {
      featureType: "transportationlabel",
      elementType: "labels.icon",
      stylers: { visibility: "off" },
    },
    { featureType: "transportationlabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "financelabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "entertainment", elementType: "geometry", stylers: { color: "#d1dbdbff" } },
    { featureType: "estate", elementType: "geometry", stylers: { color: "#d1dbdbff" } },
    { featureType: "shopping", elementType: "geometry", stylers: { color: "#d1dbdbff" } },
    { featureType: "education", elementType: "labels.text.fill", stylers: { color: "#999999ff" } },
    {
      featureType: "education",
      elementType: "labels.text.stroke",
      stylers: { color: "#ffffffff" },
    },
    { featureType: "medical", elementType: "labels.text.fill", stylers: { color: "#999999ff" } },
    { featureType: "medical", elementType: "labels.text.stroke", stylers: { color: "#ffffffff" } },
    {
      featureType: "transportation",
      elementType: "labels.text.fill",
      stylers: { color: "#999999ff" },
    },
    {
      featureType: "transportation",
      elementType: "labels.text.stroke",
      stylers: { color: "#ffffffff" },
    },
    { featureType: "road", elementType: "geometry", stylers: { visibility: "on" } },
    { featureType: "nationalway", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "provincialway", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "cityhighway", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "tertiaryway", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "fourlevelway", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "water", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "manmade", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "education", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "medical", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "scenicspots", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "transportation", elementType: "labels", stylers: { visibility: "off" } },
    {
      featureType: "entertainmentlabel",
      elementType: "labels.icon",
      stylers: { visibility: "off" },
    },
    { featureType: "estatelabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    {
      featureType: "businesstowerlabel",
      elementType: "labels.icon",
      stylers: { visibility: "off" },
    },
    { featureType: "governmentlabel", elementType: "labels.icon", stylers: { visibility: "off" } },
    { featureType: "governmentlabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "businesstowerlabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "estatelabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "entertainmentlabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "medicallabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "educationlabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "scenicspotslabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "airportlabel", elementType: "labels", stylers: { visibility: "off" } },
    { featureType: "poilabel", elementType: "labels", stylers: { visibility: "off" } },
  ],
};
